name: "machbarkeit"

services:
  backend:
    image: ghcr.io/diz-unimr/machbarkeit-backend:1.2.11
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - BASE_URL=http://localhost:3000
      - AUTH__OIDC__ISSUER_URL
      - AUTH__OIDC__CLIENT_ID
      - AUTH__OIDC__CLIENT_SECRET
      - CORS__ALLOW_ORIGIN=http://localhost:5173
      - SESSION__CROSS_DOMAIN=false
      - MDR__ENDPOINT=http://mdr:3000
      - DATABASE__URL=sqlite://db.sqlite?mode=rwc
    ports:
      - "3000:3000"

  query:
    image: ghcr.io/diz-unimr/machbarkeit-query:1.2.2
    restart: unless-stopped
    environment:
      app.log_level: trace
      feasibility.service: cql
      feasibility.base_url: http://translate:8080
      fhir_server.base_url: https://fhir.diz.uni-marburg.de/fhir
      fhir_server.auth.basic.user: diz-fhir-admin
      fhir_server.auth.basic.password: ${DIZ_FHIR_PASSWORD}
      broker.url: ws://backend:3000/feasibility/ws
      broker.auth.client_credentials.client_id: machbarkeit
      broker.auth.client_credentials.client_secret: ${AUTH__OIDC__CLIENT_SECRET}
      broker.auth.client_credentials.token_url: ${AUTH__OIDC__TOKEN_ENDPOINT}
    depends_on:
      - backend

  db:
    image: postgres:17.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mdr
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - mdr-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  mdr:
    image: ghcr.io/diz-unimr/mdr-service:1.5.0-beta.1
    restart: unless-stopped
    environment:
      database.url: postgres://postgres:postgres@db/mdr
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy

  translate:
    image: ghcr.io/diz-unimr/translate:2.0.1
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./ontology:/opt/translate/ontology:ro

volumes:
  mdr-data:
